name: Build and Release Kiero

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [Debug, Release]
        platform: [x64, Win32]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup CMake
      uses: lukka/get-cmake@latest
      
    - name: Configure CMake
      run: |
        cmake -B build -S . -A ${{ matrix.platform }} -DCMAKE_BUILD_TYPE=${{ matrix.config }}
        
    - name: Build
      run: |
        cmake --build build --config ${{ matrix.config }} --parallel
        
    - name: Debug build output
      run: |
        Write-Host "Build directory structure:"
        if (Test-Path "build") {
          Get-ChildItem -Recurse build/ | Where-Object { $_.Extension -eq ".lib" -or $_.Extension -eq ".dll" } | Select-Object FullName
        } else {
          Write-Host "Build directory not found!"
        }
      shell: powershell
      
    - name: Create artifact directory
      run: |
        New-Item -ItemType Directory -Force -Path "artifacts/${{ matrix.platform }}/${{ matrix.config }}"
      shell: powershell
        
    - name: Copy build artifacts
      run: |
        $artifactPath = "artifacts/${{ matrix.platform }}/${{ matrix.config }}"
        
        # Find and copy kiero.lib
        $kieroLib = Get-ChildItem -Recurse build/ -Filter "kiero.lib" | Select-Object -First 1
        if ($kieroLib) {
          Write-Host "Found kiero.lib at: $($kieroLib.FullName)"
          Copy-Item $kieroLib.FullName "$artifactPath/"
        } else {
          Write-Host "kiero.lib not found!"
          exit 1
        }
        
        # Copy header file
        if (Test-Path "kiero.h") {
          Copy-Item "kiero.h" "$artifactPath/"
        } else {
          Write-Host "Warning: kiero.h not found!"
        }
        
        # Find and copy MinHook lib if it exists
        $minhookLib = Get-ChildItem -Recurse build/ -Filter "minhook.lib" | Select-Object -First 1
        if ($minhookLib) {
          Write-Host "Found minhook.lib at: $($minhookLib.FullName)"
          Copy-Item $minhookLib.FullName "$artifactPath/"
        } else {
          Write-Host "minhook.lib not found (this might be expected)"
        }
        
        # Verify artifacts were created
        Write-Host "Artifacts created:"
        Get-ChildItem "$artifactPath/" | Select-Object Name
      shell: powershell
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kiero-${{ matrix.platform }}-${{ matrix.config }}
        path: artifacts/${{ matrix.platform }}/${{ matrix.config }}/
        retention-days: 30

  release:
    needs: build
    runs-on: windows-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download x64 Release artifact
      uses: actions/download-artifact@v4
      with:
        name: kiero-x64-Release
        path: x64-release
        
    - name: Download x86 Release artifact
      uses: actions/download-artifact@v4
      with:
        name: kiero-Win32-Release
        path: x86-release
        
    - name: Verify downloads and rename libraries
      run: |
        Write-Host "x64-release contents:"
        Get-ChildItem x64-release/
        Write-Host "x86-release contents:"
        Get-ChildItem x86-release/
        
        # Rename the lib files to distinguish platforms
        if (Test-Path "x64-release/kiero.lib") {
          Rename-Item "x64-release/kiero.lib" "kiero-x64.lib"
          Write-Host "Renamed x64 library"
        } else {
          Write-Host "Error: x64 kiero.lib not found!"
          exit 1
        }
        
        if (Test-Path "x86-release/kiero.lib") {
          Rename-Item "x86-release/kiero.lib" "kiero-x86.lib"
          Write-Host "Renamed x86 library"
        } else {
          Write-Host "Error: x86 kiero.lib not found!"
          exit 1
        }
      shell: powershell
        
    - name: Extract version
      id: version
      run: |
        $version = $env:GITHUB_REF -replace "refs/tags/", ""
        echo "version=$version" >> $env:GITHUB_OUTPUT
      shell: powershell
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.version }}
        name: Kiero ${{ steps.version.outputs.version }}
        draft: false
        prerelease: ${{ contains(steps.version.outputs.version, '-') }}
        body: |
          ## Kiero Library Release ${{ steps.version.outputs.version }}
          
          ### What's Included
          - `kiero-x64.lib` - 64-bit release library
          - `kiero-x86.lib` - 32-bit release library
          
          ### Usage
          1. Download the appropriate .lib file for your platform
          2. Add to your project's library dependencies
          3. Include `kiero.h` in your project (from the repository)
          4. Link against the library in your build system
          
          ### Platform Support
          - Windows x64 (Release)
          - Windows x86 (Release)
          
        files: |
          x64-release/kiero-x64.lib
          x86-release/kiero-x86.lib
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}